# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'USCFilms_HW9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for USCFilms_HW9
  pod "SwiftyJSON"
  pod "Alamofire","~> 5.2"
  pod "Kingfisher", "~> 6.0"
  pod "youtube-ios-player-helper", "~> 1.0.3"

  target 'USCFilms_HW9Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'USCFilms_HW9UITests' do
    # Pods for testing
  end

end
